name: CI

# controls when action will run
on:
  # triggers workflow on push events
  push:
  # allows workflow to be triggered manually from Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build Octave from source
      uses: ./.

    - name: Display installed files
      run: |
        ls -al $HOME/install/
        ls -al $HOME/install/bin
        ls -al $HOME/install/include
        ls -al $HOME/install/lib
        ls -al $HOME/install/share
        [ -f $HOME/install/bin/ipopt ] || exit 2
